### ISSUE TITLE
Server crashes when it isn't connected to an X11 server

### ISSUE THREAD

**Issue by Sxigames** [toxicity188/BetterHud#24]
If a server doesn't have a GPU, theres two possible outcomes 

1. If it isn't connect to a remote computer through X11 forwarding, the server starts, but none of the huds initialize and spits out this error 
```[02:42:52 INFO]: [!] Unable to save this file: assets/betterhud/textures/pixel_3.png
[02:42:52 INFO]: [!] Reason: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
[02:42:52 WARN]: java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
[02:42:52 WARN]:        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:104)
[02:42:52 WARN]:        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.manager.PlayerHeadManager.reload$lambda$20$lambda$19$lambda$18$lambda$17(PlayerHeadManager.kt:142)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.pack.PackGenerator$FileTreeBuilder.save(PackGenerator.kt:44)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.pack.PackGenerator$generate$1$saveTask$3.invoke(PackGenerator.kt:125)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.pack.PackGenerator$generate$1$saveTask$3.invoke(PackGenerator.kt:120)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.pack.PackGenerator.generate$lambda$23$lambda$21$lambda$20(PackGenerator.kt:199)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.pack.PackGenerator.generate$lambda$23$lambda$21(PackGenerator.kt:198)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.util.ListsKt.forEachAsync$lambda$6(Lists.kt:57)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.util.ListsKt$forEachAsync$1.run$lambda$3$lambda$2$lambda$0(Lists.kt:71)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.util.ListsKt$forEachAsync$1.run$lambda$3$lambda$2(Lists.kt:70)
[02:42:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[02:42:52 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable. [in thread "Thread-28"]
[02:42:52 WARN]:        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
[02:42:52 WARN]:        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
[02:42:52 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
[02:42:52 WARN]:        at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
[02:42:52 WARN]:        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
[02:42:52 WARN]:        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
[02:42:52 WARN]:        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:91)
[02:42:52 WARN]:        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:82)
[02:42:52 WARN]:        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:104)
[02:42:52 WARN]:        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
[02:42:52 WARN]:        at BetterHud-1.0.jar//kr.toxicity.hud.manager.TextManager.parseFont$lambda$80$lambda$61(TextManager.kt:448)
[02:42:52 WARN]:        ... 5 more
```

2. If the server has access to a remote graphical enviroment, and it is disconnected the server imediately crashes as seen in the video below

https://github.com/user-attachments/assets/25bc5182-44d7-499b-b821-64eb61662d42

**Comment by toxicity188** [comment]
It is your OS issue and i can't help you. it is out of my plugin's support range.
