### ISSUE TITLE
NPE hud player not found

### ISSUE THREAD

**Issue by rugiaDev** [toxicity188/BetterHud#27]
```java
Cannot invoke "kr.toxicity.hud.api.player.HudPlayer.getBukkitPlayer()" because "this.hudPlayer" is null
        at kr.toxicity.hud.addon.mmocore.player.SkillPlayer.update(SkillPlayer.java:27) ~[BetterHud-MMOCore-1.1.jar:?]
        at kr.toxicity.hud.scheduler.FoliaScheduler.asyncTaskTimer$lambda$4(FoliaScheduler.kt:68) ~[BetterHud-1.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
BetterHud-1.1.jar
BetterHud-MMOCore-1.1.jar

errors that occasionally appear during asynchronous processing
occurs when a player connects.

![image](https://github.com/user-attachments/assets/957674b1-6fd8-46ec-9f8a-f46ff7265695)

**Comment by toxicity188** [comment]
Fixed in 1.2: https://github.com/toxicity188/BetterHud-MMOCore/releases/tag/1.2
