### ISSUE TITLE
Font reading issue

### ISSUE THREAD

**Issue by SentryoZ** [toxicity188/BetterHud#28]
I got this error when tried to using custom text on cloud server (Ubuntu OS) but it run well on local server (Windows 11)

Log with debug:
```
> hud reload
[14:16:14] [Server thread/INFO]: [!] Trying to reload. please wait...
[14:16:18] [ForkJoinPool.commonPool-worker-3/INFO]: [!] Unable to load this text: default in default.yml
[14:16:18] [ForkJoinPool.commonPool-worker-3/INFO]: [!] Reason: Problem reading font data.
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: java.io.IOException: Problem reading font data.
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.desktop/java.awt.Font.createFont0(Font.java:1205)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.desktop/java.awt.Font.createFont(Font.java:1076)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.TextManager.reload$lambda$38$lambda$37(TextManager.kt:243)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.TextManager.reload$lambda$38(TextManager.kt:235)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6$lambda$5(Files.kt:43)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.YamlsKt.forEachSubConfiguration(Yamls.kt:19)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6(Files.kt:42)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7(Files.kt:41)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:29)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder$lambda$4(Files.kt:27)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEach(Files.kt:50)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:26)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml(Files.kt:39)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.TextManager.reload(TextManager.kt:234)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22$lambda$20$lambda$18$lambda$17(BetterHudImpl.kt:237)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1432)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2415)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22$lambda$20(BetterHudImpl.kt:238)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22(BetterHudImpl.kt:230)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1432)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2415)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload(BetterHudImpl.kt:250)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.api.BetterHud.reload(BetterHud.java:64)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.CommandManager.command$lambda$2$lambda$1$lambda$0(CommandManager.kt:25)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[14:16:18] [ForkJoinPool.commonPool-worker-2/INFO]: [!] Unable to load this layout: player_info in player-info.yml
[14:16:18] [ForkJoinPool.commonPool-worker-2/INFO]: [!] Reason: this text doesn't exist: default
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: java.lang.RuntimeException: this text doesn't exist: default
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.ifNull(Functions.kt:15)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.layout.LayoutGroup.text$lambda$14$lambda$13(LayoutGroup.kt:58)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.YamlsKt.forEachSubConfiguration(Yamls.kt:19)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.layout.LayoutGroup.<init>(LayoutGroup.kt:52)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.LayoutManager.reload$lambda$4$lambda$3$lambda$2(LayoutManager.kt:27)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.MapsKt.putSync(Maps.kt:32)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.LayoutManager.reload$lambda$4$lambda$3(LayoutManager.kt:26)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.LayoutManager.reload$lambda$4(LayoutManager.kt:25)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6$lambda$5(Files.kt:43)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.YamlsKt.forEachSubConfiguration(Yamls.kt:19)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6(Files.kt:42)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7(Files.kt:41)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:29)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder$lambda$4(Files.kt:27)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEach(Files.kt:50)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:26)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml(Files.kt:39)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.LayoutManager.reload(LayoutManager.kt:24)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22$lambda$20$lambda$18$lambda$17(BetterHudImpl.kt:237)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[14:16:18] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[14:16:18] [ForkJoinPool.commonPool-worker-3/INFO]: [!] Unable to load this hud: player_hud in player-hud.yml
[14:16:18] [ForkJoinPool.commonPool-worker-3/INFO]: [!] Reason: this layout doesn't exist: player_info
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: java.lang.RuntimeException: this layout doesn't exist: player_info
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.ifNull(Functions.kt:15)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.hud.HudImpl.elements$lambda$5$lambda$4(HudImpl.kt:51)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.YamlsKt.forEachSubConfiguration(Yamls.kt:19)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.hud.HudImpl.<init>(HudImpl.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload$lambda$2$lambda$1$lambda$0(HudManagerImpl.kt:26)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.MapsKt.putSync(Maps.kt:32)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload$lambda$2$lambda$1(HudManagerImpl.kt:25)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload$lambda$2(HudManagerImpl.kt:24)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6$lambda$5(Files.kt:43)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.YamlsKt.forEachSubConfiguration(Yamls.kt:19)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7$lambda$6(Files.kt:42)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml$lambda$7(Files.kt:41)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:29)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder$lambda$4(Files.kt:27)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEach(Files.kt:50)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:26)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllYaml(Files.kt:39)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload(HudManagerImpl.kt:23)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22$lambda$20$lambda$18$lambda$17(BetterHudImpl.kt:237)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1432)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2415)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22$lambda$20(BetterHudImpl.kt:238)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.util.FunctionsKt.runWithExceptionHandling(Functions.kt:49)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload$lambda$22(BetterHudImpl.kt:230)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1432)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2415)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.BetterHudImpl.reload(BetterHudImpl.kt:250)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.api.BetterHud.reload(BetterHud.java:64)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at BetterHud-1.0.jar//kr.toxicity.hud.manager.CommandManager.command$lambda$2$lambda$1$lambda$0(CommandManager.kt:25)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[14:16:18] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[14:16:20] [ForkJoinPool.commonPool-worker-3/INFO]: [BetterHud] File packed: 5.462MB -> 5.462MB
[14:16:20] [ForkJoinPool.commonPool-worker-3/INFO]: [!] Reload successful! (6595 ms)
[14:16:20] [Folia Async Scheduler Thread #3/INFO]: [BetterHudMMOCore] BetterHud reload detected - reload complete.
```

**Comment by SentryoZ** [comment]
@toxicity188 please check this

**Comment by toxicity188** [comment]
It is your OS issue and i can't help you. it is out of my plugin's support range.
