### ISSUE TITLE
exception on folia with beta-17

### ISSUE THREAD

**Issue by ewof** [toxicity188/BetterHud#4]
```
[00:21:14] [Folia Async Scheduler Thread #10/WARN]: [BetterHud] Async task for BetterHud vbeta-17 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap.computeIfAbsent(HashMap.java:1229) ~[?:?]
	at kr.toxicity.hud.nms.v1_20_R3.NMSImpl.inject(NMSImpl.kt:83) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.player.HudPlayerImpl.<init>(HudPlayerImpl.kt:50) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.manager.DatabaseManagerImpl$defaultConnector$1$1.load(DatabaseManagerImpl.kt:34) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.manager.PlayerManager$register$1$1.invoke(PlayerManager.kt:47) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.manager.PlayerManager$register$1$1.invoke(PlayerManager.kt:46) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.manager.PlayerManager$register$1.invoke$lambda$0(PlayerManager.kt:46) ~[BetterHud-beta-17.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at kr.toxicity.hud.manager.PlayerManager$register$1.invoke(PlayerManager.kt:46) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.manager.PlayerManager$register$1.invoke(PlayerManager.kt:45) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.util.PluginsKt.asyncTask$lambda$7(Plugins.kt:36) ~[BetterHud-beta-17.jar:?]
	at kr.toxicity.hud.scheduler.FoliaScheduler.asyncTask$lambda$2(FoliaScheduler.kt:40) ~[BetterHud-beta-17.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by toxicity188** [comment]
Fixed at [beta-18](https://github.com/toxicity188/BetterHud/releases/tag/beta-18)
