### ISSUE TITLE
Trouble merging Oraxen and BetterHud.

### ISSUE THREAD

**Issue by Chsui** [toxicity188/BetterHud#47]
**Required**  

1. Tell me the detail about your problem.
Trouble merging Oraxen and BetterHud.

2. Upload some screenshot or text log related your issue. such as:
```
[22:07:08] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.182.0 (Is it up to date?)
java.lang.ClassCastException: class com.google.gson.JsonObject cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonObject and com.google.gson.JsonArray are in unnamed module of loader java.net.URLClassLoader @504bae78)
	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:199) ~[gson-2.10.jar:?]
	at io.th0rgal.oraxen.pack.generation.AtlasGenerator.generateAtlasFile(AtlasGenerator.java:73) ~[oraxen-1.182.0.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:125) ~[oraxen-1.182.0.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:115) ~[oraxen-1.182.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
This is Oraxen's Error.

```
build-folder-location: Oraxen/pack
clear-build-folder: false
```
BetterHud's config.yml that i'm edited

I edit 'assets\betterhud\font\legacy_space.json' file
```
{"providers":{"type":"ttf","file":"betterhud:spaces.ttf","size":2.5,"oversample":1.0,"shift":[0.0,0.0],"skip":[]}}
```
↑Before

```
{"providers":[{"type":"ttf","file":"betterhud:spaces.ttf","size":2.5,"oversample":1.0,"shift":[0.0,0.0],"skip":[]}]}
```
↑Atfer

JSONObject to JSONArray (?) then working
Is this bug? If this is a bug, will it be possible to fix it?

3. Remember to notice your environment
- OS: Windows10
- Server Version: 1.20.1
- Server platform: Purpur-b2062

**Disclaimer**  
I do NOT provide any solution about that.

- Using informal launcher such as Feather client
- Closed-source plugin/mod such as Optifine and ItemsAdder
- Usage in hybrid bukkit such as ArcLight

**Comment by toxicity188** [comment]
Fixed in fdbc88b
Test in Modrinth when upload is done.
