### ISSUE TITLE
Update from 1.7

### ISSUE THREAD

**Issue by PSYCHEER** [toxicity188/BetterHud#52]
**Required**  
After I update from 1.7 to 1.8 or 1.9 I get these issues
```
[luckperms-worker-10/WARN]: [LuckPerms] Thread luckperms-worker-10 threw an uncaught exception
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method) ~[?:?]
	at java.base/java.lang.Thread.start(Thread.java:1553) ~[?:?]
	at java.base/java.lang.System$2.start(System.java:2577) ~[?:?]
	at java.base/jdk.internal.vm.SharedThreadContainer.start(SharedThreadContainer.java:152) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1575) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1712) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1842) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[21:05:09] [luckperms-worker-8/WARN]: [LuckPerms] Thread luckperms-worker-8 threw an uncaught exception
```
Getting this error on all plugins when BHUD is on 1.8+

[- Error log](https://pastebin.com/NXLtdu0D)

- Debian Bookworm
![{8952F82F-455F-48BB-9EE2-BBAF85381F90}](https://github.com/user-attachments/assets/c71cfa77-a78c-4d91-a3a2-bac05ab3dfff)

- Using ItemsAdder, not related as on test instance it works

**Comment by toxicity188** [comment]
Your OS max thread limit issue.
